//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "alpha")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::bravo::Entity> for Entity {
    fn to() -> RelationDef {
        super::charlie::Relation::Bravo.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::charlie::Relation::Alpha.def().rev())
    }
}

impl Related<super::bravo::Entity> for Entity {
    fn to() -> RelationDef {
        super::delta::Relation::Bravo.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::delta::Relation::Alpha.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
